.TH "array" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
array \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <array\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void ** \fBdata\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBdata_size\fP"
.br
.ti -1c
.RI "uint32_t \fBstarting_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array structure 
.SH "Member Data Documentation"
.PP 
.SS "void** array::data"
Contains the data array containing elements 
.SS "uint32_t array::data_size"
Number of available data elements 
.SS "uint32_t array::size"
Number of elements in the array 
.SS "uint32_t array::starting_size"
Statring size 

.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
