.TH "funcops.h" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcops.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '_commons\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef bool(* \fBsearch_predicate_t\fP) (void *element, void *passed_data)"
.br
.ti -1c
.RI "typedef int(* \fBcmp_func_t\fP) (const void *a, const void *b)"
.br
.ti -1c
.RI "typedef void(* \fBkey_deallocator_func_t\fP) (void *a)"
.br
.ti -1c
.RI "typedef void(* \fBvalue_deallocator_func_t\fP) (void *a)"
.br
.ti -1c
.RI "typedef uint32_t(* \fBhash_function_t\fP) (void *)"
.br
.ti -1c
.RI "typedef bool(* \fBeq_function_t\fP) (void *, void *)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBuint32_hash_function\fP (void *integer)"
.br
.RI "\fIConverts uint32_t passed in as void* into hash\&. \fP"
.ti -1c
.RI "bool \fBuint32_eq_function\fP (void *a, void *b)"
.br
.ti -1c
.RI "uint32_t \fBuint64_hash_function\fP (void *integer)"
.br
.RI "\fIConverts uint64_t passed in as void* into hash\&. \fP"
.ti -1c
.RI "bool \fBuint64_eq_function\fP (void *a, void *b)"
.br
.ti -1c
.RI "uint32_t \fBstring_hash_function\fP (void *string)"
.br
.RI "\fIConverts char* passed in as void* into hash\&. \fP"
.ti -1c
.RI "bool \fBstring_eq_function\fP (void *a, void *b)"
.br
.RI "\fICompares two char* values passed in as void*\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* cmp_func_t) (const void *a, const void *b)"

.SS "typedef bool(*  eq_function_t) (void *, void *)"

.SS "typedef uint32_t(*  hash_function_t) (void *)"

.SS "typedef void(* key_deallocator_func_t) (void *a)"

.SS "typedef bool(* search_predicate_t) (void *element, void *passed_data)"

.SS "typedef void(* value_deallocator_func_t) (void *a)"

.SH "Function Documentation"
.PP 
.SS "bool string_eq_function (void * a, void * b)"

.PP
Compares two char* values passed in as void*\&. Uses strcmp\&. 
.SS "uint32_t string_hash_function (void * string)"

.PP
Converts char* passed in as void* into hash\&. Hash type is uint32_t\&. 
.SS "bool uint32_eq_function (void * a, void * b)"
Compares two uint32_t values passed in as void* 
.SS "uint32_t uint32_hash_function (void * integer)"

.PP
Converts uint32_t passed in as void* into hash\&. Hash type is uint32_t\&. 
.SS "bool uint64_eq_function (void * a, void * b)"
Compares two uint64_t values passed in as void* 
.SS "uint32_t uint64_hash_function (void * integer)"

.PP
Converts uint64_t passed in as void* into hash\&. Hash type is uint32_t\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
