.TH "hash_pair_t" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash_pair_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents hash pair 
.SH "Member Data Documentation"
.PP 
.SS "void* hash_pair_t::data"

.SS "void* hash_pair_t::key"


.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
