.TH "hmap.h" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '_commons\&.h'\fP
.br
\fC#include 'funcops\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhash_pair_t\fP"
.br
.ti -1c
.RI "struct \fBhash_table_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHASH_STARTING_SIZE\fP   97"
.br
.ti -1c
.RI "#define \fBFREE_CELL\fP   0"
.br
.ti -1c
.RI "#define \fBDELETED_CELL\fP   ((void*)1)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBhash_it_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhash_table_t\fP * \fBcreate_table\fP (\fBhash_function_t\fP hash_fn, \fBeq_function_t\fP cmpr_fn)"
.br
.RI "\fICreates new hash table\&. \fP"
.ti -1c
.RI "void \fBdestroy_table\fP (\fBhash_table_t\fP *table)"
.br
.RI "\fIDeallocates table\&. \fP"
.ti -1c
.RI "bool \fBtable_contains\fP (\fBhash_table_t\fP *table, void *key)"
.br
.ti -1c
.RI "void * \fBtable_get\fP (\fBhash_table_t\fP *table, void *key)"
.br
.RI "\fIReturns value of key in the table\&. \fP"
.ti -1c
.RI "void \fBtable_set\fP (\fBhash_table_t\fP *table, void *key, void *data)"
.br
.RI "\fISets the key in the table to the data\&. \fP"
.ti -1c
.RI "bool \fBtable_remove\fP (\fBhash_table_t\fP *table, void *key)"
.br
.RI "\fIRemoves key from the table\&. \fP"
.ti -1c
.RI "uint32_t \fBtable_size\fP (\fBhash_table_t\fP *table)"
.br
.ti -1c
.RI "\fBhash_table_t\fP * \fBcopy_table\fP (\fBhash_table_t\fP *table)"
.br
.ti -1c
.RI "void * \fBhash_it_next\fP (\fBhash_table_t\fP *table, \fBhash_it_t\fP *iterator)"
.br
.ti -1c
.RI "\fBhash_table_t\fP * \fBcreate_uint32_table\fP ()"
.br
.ti -1c
.RI "\fBhash_table_t\fP * \fBcreate_uint64_table\fP ()"
.br
.ti -1c
.RI "\fBhash_table_t\fP * \fBcreate_string_table\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DELETED_CELL   ((void*)1)"

.SS "#define FREE_CELL   0"

.SS "#define HASH_STARTING_SIZE   97"

.SH "Typedef Documentation"
.PP 
.SS "typedef uint32_t \fBhash_it_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBhash_table_t\fP* copy_table (\fBhash_table_t\fP * table)"
Copies table to another table\&. 
.SS "\fBhash_table_t\fP* create_string_table ()"
Creates table for char* string keys\&. 
.SS "\fBhash_table_t\fP* create_table (\fBhash_function_t\fP hash_fn, \fBeq_function_t\fP cmpr_fn)"

.PP
Creates new hash table\&. This hash table will use provided hash_fn and cmpr_fn to hash/compare keys\&. Default size of inner table is HASH_STARTING_SIZE\&. 
.SS "\fBhash_table_t\fP* create_uint32_table ()"
Creates table for uint32_t keys\&. 
.SS "\fBhash_table_t\fP* create_uint64_table ()"
Creates table for uint64_t keys\&. 
.SS "void destroy_table (\fBhash_table_t\fP * table)"

.PP
Deallocates table\&. Removes all data from the table and table itself from memory\&. Will NOT deallocate table keys nor entries! 
.SS "void* hash_it_next (\fBhash_table_t\fP * table, \fBhash_it_t\fP * iterator)"
Returns value from iterator and moves iterator to next element\&. 
.SS "bool table_contains (\fBhash_table_t\fP * table, void * key)"
Returns whether key is in the table or not\&. 
.SS "void* table_get (\fBhash_table_t\fP * table, void * key)"

.PP
Returns value of key in the table\&. Returns NULL if key is not in the table\&. 
.SS "bool table_remove (\fBhash_table_t\fP * table, void * key)"

.PP
Removes key from the table\&. Returns true if operation was done successfully, false if there was no such key\&. 
.SS "void table_set (\fBhash_table_t\fP * table, void * key, void * data)"

.PP
Sets the key in the table to the data\&. Will remove old key-data pair if it exists (does not deallocate old data value!)\&. 
.SS "uint32_t table_size (\fBhash_table_t\fP * table)"
Returns number of elements in the table\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
