.TH "queue_element" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue_element \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fB__pool_c\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBqueue_element_t\fP * \fBprevious\fP"
.br
.ti -1c
.RI "\fBqueue_element_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool queue_element::__pool_c"

.SS "void* queue_element::data"

.SS "\fBqueue_element_t\fP* queue_element::next"

.SS "\fBqueue_element_t\fP* queue_element::previous"


.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
