.TH "random_generator" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random_generator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <random\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBstate\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Random generator state\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint64_t random_generator::state[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
