.TH "rb_node" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rb_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <btree\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBinfo\fP"
.br
.ti -1c
.RI "int \fBred\fP"
.br
.ti -1c
.RI "struct \fBrb_node\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBrb_node\fP * \fBright\fP"
.br
.ti -1c
.RI "struct \fBrb_node\fP * \fBparent\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* rb_node::info"

.SS "void* rb_node::key"

.SS "struct \fBrb_node\fP* rb_node::left"

.SS "struct \fBrb_node\fP* rb_node::parent"

.SS "int rb_node::red"

.SS "struct \fBrb_node\fP* rb_node::right"


.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
