.TH "rb_tree" 3 "Mon Jan 4 2016" "Version v0.2" "libds" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rb_tree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <btree\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmp_func_t\fP \fBcmp_func\fP"
.br
.ti -1c
.RI "\fBkey_deallocator_func_t\fP \fBkey_deallocator_func\fP"
.br
.ti -1c
.RI "\fBvalue_deallocator_func_t\fP \fBvalue_deallocator_func\fP"
.br
.ti -1c
.RI "\fBrb_node_t\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBrb_node_t\fP * \fBnil\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBcmp_func_t\fP rb_tree::cmp_func"

.SS "\fBkey_deallocator_func_t\fP rb_tree::key_deallocator_func"

.SS "\fBrb_node_t\fP* rb_tree::nil"

.SS "\fBrb_node_t\fP* rb_tree::root"

.SS "\fBvalue_deallocator_func_t\fP rb_tree::value_deallocator_func"


.SH "Author"
.PP 
Generated automatically by Doxygen for libds from the source code\&.
